version: "3.7"

services:
    db:
        image: mongo
        restart: always
        container_name: "db_node-api"
        environment:
            - MONGO_DATA-DIR=/data/db
        ports:
            - 27018:27017
        expose:
            - "27017"
        volumes:
            - ./data/db:/data/db:z
        command: mongod --smallfiles
    app:
        build: .
        image: gabriel-barreto/nodeapi:node
        container_name: "app_node-api"
        # ==> To Production
        # context: .
        # dockerfile: Dockerfile-production
        ports:
            - 5555:5000
        volumes:
            - .:/usr/app:z
        links:
            - "db:db"
        environment:
            APPPATH: "/usr/app"
